% リファレンスの状態量の場合の観測値を出力
function  Y_bar = calcG(X_bar,xve,xvg,constant)
    deltaT = X_bar(1);
    xvs = X_bar(2:7);
    T = 1/constant.lightSpeed * ...
         ((xve(1) + xvg(1) - xvs(1))^2 + ...
          (xve(2) + xvg(2) - xvs(2))^2 +....
          (xve(3) + xvg(3) - xvs(3))^2)^0.5 + deltaT;
    
    theta = atan2(xve(2) + xvg(2) - xvs(2) + xvs(5)*(T-deltaT)...
                                , xve(1) + xvg(1) - xvs(1) + xvs(4)*(T-deltaT));
    phi = atan( (xve(3) + xvg(3) - xvs(3) + xvs(6)*(T-deltaT))/...
                                   ((xve(2) + xvg(2) - xvs(2) + xvs(5) *(T-deltaT))^2 ...
                                  + (xve(1) + xvg(1) - xvs(1) + xvs(4) *(T-deltaT))^2)^0.5 );
   Y_bar = [T;theta;phi];
    
end